### PR TITLE
added missing api call, show username in navbar

### PR DESCRIPTION
**Pull request by qvalentin**

### CODE REVIEW

**Comment by qvalentin** [comment]
image

**Comment by qvalentin** [comment]
check out: 
https://storybook.filefighter.de/?path=/story/filesystem--default

**Review by open-schnick — APPROVED** [review]
works on my machine. Cannot really say to much about the code. I think we should not add a rename button there. I would add either an overwritten context menu or a button where the "share" button is to edit, share, download or delete a single file.

**Comment by open-schnick** [comment]
But we can let the "rename" button there for now.

**Pull request merged**
