### PR TITLE
Filesytem basics and navigation

### PR DESCRIPTION
**Pull request by qvalentin**

### CODE REVIEW

**Comment by qvalentin** [comment]
Go to localhost/file

**Comment by open-schnick** [comment]
branch is not a feature branch sadface

**Comment by open-schnick** [comment]
@qvalentin when using backwards and forwards key of the browser session
content doesnt reload.

**Comment by open-schnick** [comment]
also you should provide a link on the main page after loggin in to quickly navigate to it.

**Review by Gimleux — APPROVED** [review]

**Comment by Gimleux** [comment]
Requests are solved in [PR 22](https://github.com/FileFighter/WebApp/pull/22)

**Comment by qvalentin** [comment]
> Requests are solved in [PR 22](https://github.com/FileFighter/WebApp/pull/22)

<3

**Review by Gimleux — APPROVED** [review]

**Pull request merged**
